apiVersion: v1
kind: Service
metadata:
  name: three-tier-service
  namespace: default
spec:
  selector:
    app: three-tier-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
